###############################################################################
# Site settings
###############################################################################
title: Anderson Paschoalon
description: 'A front-end for my academic formation, projects, and some more stuff.' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://andersonpaschoalon.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# logo removed
# logo: "/assets/img/branding/MVM-logo-full.svg"
# logo removed
# logo-icon: "/assets/img/branding/MVM-symbol.svg"
# logo-icon-SEO: "/assets/img/branding/MVM-symbol-black.png" # must be a non SVG file
logo-icon-SEO: "/assets/img/icons/SEO-icon.png" # must be a non SVG file
# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"
# logo dark removed
# logo-dark: "/assets/img/branding/MVM-logo-full-dark.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed
# alpha (not stable), beta (stable, has known small bugs), none (no known bugs)
# Major update (technology/website structure) | Update (post, small changes) | Hotfix 
version: "beta-v1.1.2"

###############################################################################
# HEADER INFORMATION
###############################################################################
header-title: Anderson Paschoalon
header-description: C/C++/C# desktop and embedded-systems developer, master and self-made researcher, machine learning enthusiast, and game modder.

###############################################################################
# Assets Paths
###############################################################################
path-icon:  /assets/img/icon/
path-photos: /assets/img/photos/
path-posts: /assets/img/posts/
path-pages: /assets/img/pages/
path-globals: /assets/img/globals/
path-pdf: /assets/pdf/

# Author settings
author: Anderson Paschoalon # add your name

###############################################################################
# Contact links
###############################################################################
email: anderson.paschoalon@gmail.com # Add your Email address
phone: # Add your Phone number
website: # Add your website
linkedin: https://br.linkedin.com/in/anderson-paschoalon-61054175 # Add your Linkedin handle
github: https://github.com/AndersonPaschoalon # Add your Github handle
twitter: # Add your Twitter handle
bandcamp:  # Add your Bandcamp username
researchgate: https://www.researchgate.net/profile/Anderson-Paschoalon-2
intrig: https://intrig.dca.fee.unicamp.br/people/
lattes: http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K8136551T3

###############################################################################
# Pages
###############################################################################
# main pages
page-home: /index.html
page-publications: /archive.html
page-projects: /projects.html
page-curriculum: /curriculum.html
page-bio: /bio.html
page-blog: /blog.html # todo
page-404.html: /404.html
page-under-construction: /under-construction.html
# projects
page-ethermonitor: /proj-ethermonitor.html
page-simitar: /simitar.html
page-dsilhand: /dsilhand.html
page-moforgit: /moforgit.html
page-quest-dialog-manager: /questdialogmanager.html
# publications


# Disqus
#discus_identifier: amaynez-github-io # Add your discus identifier
#comments_curtain: yes # leave empty to show the disqus embed directly
discus_identifier:
comments_curtain: yes 

# Tracker
#analytics: G-R8SZS2YBZK
#fbadmin: ar.maybach
analytics: 
fbadmin: 


# Paginate
# paginate: 6
paginate: 1024 # no limit for pages
paginate_path: 'page:num'
words_per_minute: 200

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]